# Generated by Django 5.0.7 on 2024-07-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_auto_20240719_1523"),
    ]

    operations = [
        migrations.RunSQL(
            """
                          INSERT INTO store_collection (title)
                          VALUES ('collection1')
                          """,
            """
                          DELETE FROM store_collection
                          WHERE title='collection1'
                          """,
        )
    ]
